name: '#HollywoodREBEL'
favicon: null
layout_spectrum: 0.12402
typography_spectrum: 0.06932
title: '#TheGrid testing.'
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-38685198-2
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#040000'
    - '#818242'
    - '#d30c03'
    - '#fa4f1c'
  brandStrength: 0.5625
  lightness: 0.875
  saturation: 0.6875
  rhythmicContrast: 1
purpose: []
