name: '#HollywoodREBEL'
favicon: null
layout_spectrum: 0.95304
typography_spectrum: 0.06743
title: '#TheGrid testing.'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-38685198-2
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#ffffff'
    - '#909090'
    - '#3f3f3f'
    - '#aa0000'
  brandStrength: 0.75
  lightness: 0.5
  saturation: 0.5625
  rhythmicContrast: 0
purpose: []
