title: 'Hollywood REBEL tests #TheGrid'
purpose: []
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
color:
  saturation: 0.625
  brandStrength: 0.875
  rhythmicContrast: 1
  brandColors:
    - '#000000'
    - '#373737'
    - '#606060'
    - '#b6b6b6'
    - '#ebebeb'
  lightness: 0.5
cta:
  bucket: null
  version: null
  domain: null
analytics:
  twitter: null
  google: UA-38685198-2
  facebook: null
name: '#HollywoodREBEL'
favicon: null
opengraph:
  image: null
  type: null
  appId: null
typography_spectrum: 0.1015037
layout_spectrum: 0
