name: '#HollywoodREBEL'
favicon: null
layout_spectrum: 0.36183
typography_spectrum: 0.06447
title: 'Hollywood REBEL tests #TheGrid'
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-38685198-2
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#010206'
    - '#133747'
    - '#2b6d87'
    - '#75a5bb'
    - '#b6ceda'
  brandStrength: 1
  lightness: 0.4375
  saturation: 0.875
  rhythmicContrast: 0.75
purpose: []
