name: '#HollywoodREBEL'
favicon: null
layout_spectrum: 0.12327
typography_spectrum: 0.08307
title: '#TheGrid testing.'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-38685198-2
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#033d86'
    - '#010103'
    - '#b4d6fc'
    - '#5c5a8c'
    - '#858f94'
  brandStrength: 0.875
  lightness: 0.8125
  saturation: 0.625
  rhythmicContrast: 1
purpose: []
