name: HollywoodREBEL
favicon: null
layout_spectrum: 0.40872519719414413
typography_spectrum: 0.6314110248349607
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-38685198-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.8449791411403567
  lightness: 0.325709733646363
  saturation: 0.730729108909145
  rhythmicContrast: 0.6862803241237998
purpose: []
