name: '#HollywoodREBEL'
favicon: null
layout_spectrum: 0.04696
typography_spectrum: 0.05176
title: '#TheGrid testing.'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-38685198-2
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#040000'
    - '#818242'
    - '#d30c03'
    - '#fa4f1c'
  brandStrength: 0.9375
  lightness: 0.5
  saturation: 0.625
  rhythmicContrast: 1
purpose: []
