name: '#HollywoodREBEL'
favicon: null
layout_spectrum: 0.6189
typography_spectrum: 0
title: ICU
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-38685198-2
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#000000'
    - '#4cd964'
    - '#5f5f5f'
    - '#007aff'
  brandStrength: 0.875
  lightness: 1
  saturation: 0.5625
  rhythmicContrast: 0.25
purpose: []
