typography_spectrum: 0.10997282154858112
color:
  saturation: 0.10908033046871424
  brandStrength: 0.9943949657026678
  rhythmicContrast: 0.7456058899406344
  brandColors:
    - '#B9121B'
    - '#4C1B1B'
    - '#F6E497'
    - '#FCFAE1'
    - '#BD8D46'
  lightness: 0.7875801539048553
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.8491469291038811
analytics:
  twitter: '#HollywoodREBEL'
  google: UA-38685198-2
  facebook: null
name: '#HollywoodREBEL'
cta:
  bucket: null
  version: null
  domain: null
favicon: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
title: 'Hollywood REBEL tests #TheGrid!'
description: >-
  *This is a test of "artificial intelligence" financed to assist our business
  needs.
purpose: []
