name: '#HollywoodREBEL'
favicon: null
layout_spectrum: 0.1168
typography_spectrum: 0.04644
title: '#TheGrid testing.'
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-38685198-2
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#c8d4e0'
    - '#9aabb5'
    - '#677c8c'
    - '#1a364e'
  brandStrength: 0.75
  lightness: 0.5625
  saturation: 0.6875
  rhythmicContrast: 1
purpose: []
