name: '#HollywoodREBEL'
favicon: null
layout_spectrum: 0.94581
typography_spectrum: 0.07345
title: '#TheGrid testing.'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-38685198-2
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#ffffff'
    - '#909090'
    - '#3f3f3f'
    - '#aa0000'
  brandStrength: 0.625
  lightness: 0.4375
  saturation: 1
  rhythmicContrast: 0
purpose: []
