name: '#HollywoodREBEL'
favicon: null
layout_spectrum: 1
typography_spectrum: 0.05659
title: '#TheGrid testing.'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-38685198-2
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#0b0704'
    - '#8c5d43'
    - '#b98d68'
    - '#d0a379'
    - '#46352b'
  brandStrength: 1
  lightness: 0.6875
  saturation: 0.5625
  rhythmicContrast: 0.5
purpose: []
