name: '#HollywoodREBEL'
favicon: null
layout_spectrum: 0.89343
typography_spectrum: 0.05659
title: '#TheGrid testing.'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-38685198-2
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#171916'
    - '#af7140'
    - '#6d6862'
    - '#a4b6ca'
  brandStrength: 1
  lightness: 0.75
  saturation: 0.6875
  rhythmicContrast: 0
purpose: []
